name: Windows RDP Tunnel (ngrok v3+)

on: workflow_dispatch

jobs:
  expose-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Download ngrok v3
      shell: powershell
      run: |
        # Updated download URL for ngrok v3
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Authenticate ngrok
      shell: powershell
      run: |
        .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start ngrok tunnel
      shell: powershell
      run: |
        $ngrokExe = "$pwd\ngrok\ngrok.exe"
        
        # Start ngrok with version check
        & $ngrokExe version
        Start-Process $ngrokExe -ArgumentList "tcp 3389" -NoNewWindow
        
        # Wait and get URL
        Start-Sleep -Seconds 15
        $tunnels = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels
        $publicUrl = $tunnels.tunnels[0].public_url
        Write-Host "RDP URL: $publicUrl"

    - name: Keep alive
      shell: powershell
      run: while ($true) { Start-Sleep -Seconds 60 }
