- name: Start ngrok tunnel
  shell: powershell
  run: |
    # Start ngrok with logging
    $logPath = "$pwd\ngrok.log"
    Start-Process -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389 --log $logPath" -NoNewWindow
    
    # Verify ngrok process
    Start-Sleep -Seconds 5
    if (-not (Get-Process ngrok -ErrorAction SilentlyContinue)) {
        Write-Host "::error::Ngrok failed to start!"
        Get-Content $logPath -ErrorAction SilentlyContinue | Write-Host
        exit 1
    }

    # Extended retry logic
    $maxRetries = 10
    $retryCount = 0
    $publicUrl = $null
    
    while ($retryCount -lt $maxRetries -and -not $publicUrl) {
        try {
            $response = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels -ErrorAction Stop
            $publicUrl = $response.tunnels[0].public_url
            Write-Host "::add-mask::$publicUrl"
            Write-Host "RDP URL: $publicUrl"
        }
        catch {
            Write-Host "Attempt $($retryCount+1)/$maxRetries - Waiting for ngrok API..."
            Get-Content $logPath -Tail 10 -ErrorAction SilentlyContinue | Write-Host
            Start-Sleep -Seconds 10
            $retryCount++
        }
    }

    if (-not $publicUrl) {
        Write-Host "::error::Failed to get tunnel URL after $maxRetries attempts"
        Get-Content $logPath -ErrorAction SilentlyContinue | Write-Host
        Get-Process ngrok | Stop-Process -Force
        exit 1
    }
